version: "3.8"

services: 
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: host.docker.internal              
      DB_PORT: ${DB_PORT}                    
      DB_USER: ${DB_USER}                    
      DB_PASSWORD: ${DB_PASSWORD}            
      DB_DATABASE: ${DB_DATABASE}             
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
